- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.3.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
  - id: flake8
  - id: trailing-whitespace
  # - id: requirements-txt-fixer

- repo: git://github.com/pre-commit/mirrors-pylint
  sha: v1.3.1
  hooks:
  - id: pylint
    args:
    - --disable import-error
    - --disable too-few-public-methods
    - --disable redefined-builtin
    - --disable protected-access
    - --disable no-self-use
    - --disable too-many-public-methods
    - --disable invalid-name
    - --disable cyclic-import
    - --disable attribute-defined-outside-init

- repo: git://github.com/asottile/reorder_python_imports
  sha: ab361ca1e4dfaeea0c4eab464c799e02cb306ab3
  hooks:
  - id: reorder-python-imports
    args:
      - --diff-only

- repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
  sha: v0.3.2
  hooks:
  - id: pep257
